### ISSUE TITLE
Specifying destination directory for downloads

### ISSUE THREAD

**Issue by eunyoung14** [alpacanetworks/alpacon-cli#4]
Hello,

I tried to use `download` command, and I found that it does not support specifying a destination path. It would be great if I could do that!

- If not specified, download it in the current directory. (just like now)
- If specified and the path is a directory, download it in the specified directory.
- If specified and the path is a file, download it and name it to the specified argument.

Expected command:

```
alpacon download <server>:<src path> [dst_path]
```

**Comment by royroyee** [comment]
Thank you for your feedback.

The improvements have been implemented as follows and will be available in the 0.0.5 release:

Similar to the scp command, **specifying the destination directory for downloads is now required**.
The commands for download and upload have been unified under the name cp.


```bash
$ alpacon cp [SOURCE] [DESTINATION]

# To Upload Files
$ alpacon cp /Users/alpacon.txt myserver:/home/alpacon/

# To Download Files
$ alpacon cp myserver:/home/alpacon/alpacon.txt .
```
- [SERVER NAME]:[PATH]: This notation denotes the server's name and the file's path for FTP operations.
